name: guardacorpo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  permission_handler: ^8.1.2
  url_launcher: ^6.0.10
  native_admob_flutter: ^1.5.0
  syncfusion_flutter_pdfviewer: ^19.3.44-beta
  flutter_webview_pro: ^1.0.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/index.jpg
    - assets/images/logo.png
    - assets/images/menu.jpg
    - assets/images/normas.jpg
    - assets/images/dds.jpg
    - assets/images/epi.jpg
    - assets/images/treinamentos.jpg
    - assets/images/cid.jpg
    - assets/images/mapa.jpg
    - assets/images/sinalizacao.jpg
    - assets/images/datas.jpg
    - assets/images/historia.jpg
    - assets/images/tecnico.jpg
    - assets/images/nbr.jpg
    - assets/images/ppp.jpg
    - assets/images/incendio.jpg
    - assets/images/acidente.jpg
    - assets/images/riscos.jpg
    - assets/images/esocial.jpg
    - assets/images/clt.jpg
    - assets/images/aso.jpg
    - assets/images/cnae.jpg
    - assets/pdf_nr/nr1.pdf
    - assets/pdf_nr/nr2.pdf
    - assets/pdf_nr/nr3.pdf
    - assets/pdf_nr/nr4.pdf
    - assets/pdf_nr/nr5.pdf
    - assets/pdf_nr/nr6.pdf
    - assets/pdf_nr/nr7.pdf
    - assets/pdf_nr/nr8.pdf
    - assets/pdf_nr/nr9.pdf
    - assets/pdf_nr/nr10.pdf
    - assets/pdf_nr/nr11.pdf
    - assets/pdf_nr/nr11anexo1.pdf
    - assets/pdf_nr/nr12.pdf
    - assets/pdf_nr/nr13.pdf
    - assets/pdf_nr/nr14.pdf
    - assets/pdf_nr/nr15.pdf
    - assets/pdf_nr/nr15anexo1.pdf
    - assets/pdf_nr/nr15anexo2.pdf
    - assets/pdf_nr/nr15anexo3.pdf
    - assets/pdf_nr/nr15anexo4.pdf
    - assets/pdf_nr/nr15anexo5.pdf
    - assets/pdf_nr/nr15anexo6.pdf
    - assets/pdf_nr/nr15anexo7.pdf
    - assets/pdf_nr/nr15anexo8.pdf
    - assets/pdf_nr/nr15anexo9.pdf
    - assets/pdf_nr/nr15anexo10.pdf
    - assets/pdf_nr/nr15anexo11.pdf
    - assets/pdf_nr/nr15anexo12.pdf
    - assets/pdf_nr/nr15anexo13.pdf
    - assets/pdf_nr/nr15anexo13a.pdf
    - assets/pdf_nr/nr15anexo14.pdf
    - assets/pdf_nr/nr16.pdf
    - assets/pdf_nr/nr17.pdf
    - assets/pdf_nr/nr17anexo1.pdf
    - assets/pdf_nr/nr17anexo2.pdf
    - assets/pdf_nr/nr18.pdf
    - assets/pdf_nr/nr19.pdf
    - assets/pdf_nr/nr20.pdf
    - assets/pdf_nr/nr21.pdf
    - assets/pdf_nr/nr22.pdf
    - assets/pdf_nr/nr23.pdf
    - assets/pdf_nr/nr24.pdf
    - assets/pdf_nr/nr25.pdf
    - assets/pdf_nr/nr26.pdf
    - assets/pdf_nr/nr27.pdf
    - assets/pdf_nr/nr28.pdf
    - assets/pdf_nr/nr29.pdf
    - assets/pdf_nr/nr30.pdf
    - assets/pdf_nr/nr30anexo1.pdf
    - assets/pdf_nr/nr30anexo2.pdf
    - assets/pdf_nr/nr31.pdf
    - assets/pdf_nr/nr32.pdf
    - assets/pdf_nr/nr33.pdf
    - assets/pdf_nr/nr34.pdf
    - assets/pdf_nr/nr35.pdf
    - assets/pdf_nr/nr36.pdf
    - assets/pdf_nr/nr37.pdf
    - assets/mapaderisco.pdf



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/segoeresgular.ttf
    - family: Segoe Bold
      fonts:
        - asset: assets/fonts/segoebold.ttf
    - family: Segoe Black
      fonts:
        - asset: assets/fonts/segoeblack.ttf
    - family: Segoe Light
      fonts:
        - asset: assets/fonts/segoelight.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
